name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_case:
          - CanTp_CancelReceive
          - CanTp_CancelTransmit
          - CanTp_ReadParameter
          - CanTp_ChangeParameter
          # - CanTp_GetVersionInfo
          - CanTp_Init
          # - CanTp_Main
          - CanTp_RxInd
          - CanTp_Shutdown
          - CanTp_Transmit
          # - CanTp_TxConf
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Test execution
      run: ./bin/tests ${{ matrix.test_case }}
